name: Prism
version: '1.4.1'
main: org.kittycatmeow.prism.Prism
api-version: '1.21'
load: STARTUP
authors: [ _kittycatmeow ]
description: Prism SMP Plugin
commands:
  debug:
    permission: op
  prism:
    description: Plugin information
    usage: /prism
  fix:
    description: Replace your power in case of a bug or you just did something stupid
    usage: /fix
  toggleinhandsneaking:
    description: Toggles whether or not sneaking will trigger a passive ability when your power item is not in your hand
    usage: /toggleinhandsneaking
  getrerollitem:
    description: Get a certain number of reroll items
    permission: prism.getrerollitem
    permission-message: You do not have permission to utilize this command
    usage: /getrerollitem [count (default 1)]
  givererollitem:
    description: Give a certain number of reroll items to yourself or another player
    permission: prism.givererollitem
    permission-message: You do not have permission to utilize this command
    usage: /givererollitem <player> [count (default 1)]
  givererollall:
    description: Give everyone a certain number of reroll items
    permission: prism.givererollall
    permission-message: You do not have permission to utilize this command
    usage: /givererollall [count (default 1)]
  setpower:
    description: Set the power of a player
    permission: prism.setpower
    permission-message: You do not have permission to utilize this command
    usage: /setpower <player> <power>
  reroll:
    description: Gives a random power to yourself or another player
    permission: prism.reroll
    permission-message: You do not have permission to utilize this command
    usage: /reroll [player (default self)]
  rerollall:
    description: Gives a random power to all online players
    permission: prism.rerollall
    permission-message: You do not have permission to utilize this command
    usage: /rerollall
  reloadpowers:
    description: Reloads the powers for all online players
    permission: prism.reloadpowers
    permission-message: You do not have permission to utilize this command
    usage: /reloadpowers
  clearcooldowns:
    description: Clears all the ability cooldowns for all players
    permission: prism.clearcooldowns
    permission-message: You do not have permission to utilize this command
    usage: /clearcooldowns
    aliases: /clearcd